### ISSUE TITLE
Not Able to Implement

### ISSUE THREAD

**Issue by sansingh84** [jrosen081/PDFDrawingView#1]
if let path = Bundle.main.path(forResource: "sample", ofType: "pdf"){
            if let pdfDocument = PDFDocument(url: URL(fileURLWithPath: path)){
                pdfView.displayMode = .singlePage
                pdfView.autoScales = true
                pdfView.displayDirection = .horizontal
                pdfView.document = pdfDocument
                
                let pdfDrawer = PDFDrawingView(frame: self.pdfView.bounds, document: pdfDocument, delegate: self as? PDFDelegate)
                pdfDrawer.drawingKey = PDFDrawingView.DrawingKeys.draw
                pdfDrawer.highlightColor = UIColor.red

I am not able to perform anything on PDF, always getting one message " PDFHighlighter_POC[5867:216542] PDFAnnotations's setValue:forAnnotationKey: failed. PDF document's user permissions does not allow annotation modifications." Can you please share with a sample project.

Thanks in advance.

**Comment by jrosen081** [comment]
Hey,

I am trying to recreate this issue to see if it is a PDFKit/PDF issue or a PDFDrawingView issue. What do you mean by "I am not able to perform anything on PDF"? I tried adding an annotation onto a PDFDocument that the drawing view had, and I did not get any errors. The issue seems to be, based on the error message, that the PDF you are using has some sort of permissions not letting you do anything.

Thanks,
Jack

**Comment by sansingh84** [comment]
Hi,

Thanks for the response, if it is possible can you please share a sample app.

Regards,
Sandeep

On 21-Feb-2019, at 8:09 PM, jrosen081 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

I am trying to recreate this issue to see if it is a PDFKit/PDF issue or a PDFDrawingView issue. What do you mean by "I am not able to perform anything on PDF"? I tried adding an annotation onto a PDFDocument that the drawing view had, and I did not get any errors. The issue seems to be, based on the error message, that the PDF you are using has some sort of permissions not letting you do anything.

Thanks,
Jack

**Comment by sansingh84** [comment]
I have attached the sample project in which I tried to run the Highlight functionality using PDFDrawing POD. As I am new in IOS development, request you to please send me a sample project where I can perform Highlight annotation.

Thanks in advance.

Regards,
Sandeep





On 21-Feb-2019, at 8:12 PM, sandeep singh <sandeep.singh30@outlook.com<mailto:sandeep.singh30@outlook.com>> wrote:

Hi,

Thanks for the response, if it is possible can you please share a sample app.

Regards,
Sandeep

On 21-Feb-2019, at 8:09 PM, jrosen081 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

I am trying to recreate this issue to see if it is a PDFKit/PDF issue or a PDFDrawingView issue. What do you mean by "I am not able to perform anything on PDF"? I tried adding an annotation onto a PDFDocument that the drawing view had, and I did not get any errors. The issue seems to be, based on the error message, that the PDF you are using has some sort of permissions not letting you do anything.

Thanks,
Jack

**Comment by sansingh84** [comment]
Hi Jack, 

Thanks for the reply, as per your suggestion I changed the PDF File & that message "PDF document's user permissions does not allow annotation modifications." is not coming. But still I am not able to perform Highlighter annotation on pdf. 

I followed the step which you had mentioned : 
1.Create a PDF Document using PDFKit.
2.Import using CocoaPods 
3.Use the constructor method.
4.pdfDrawer.drawingKey = PDFDrawingView.DrawingKeys.highlight
5.pdfDrawer.highlightColor = UIColor.yellow 

Can you please share a sample app so I can see where I am doing mistake.

Thanks in advance.

Regards,
Sandeep

**Comment by jrosen081** [comment]
Hello Sandeep,

As per your request, I have added a <a href = "https://github.com/jrosen081/PDFDrawingView/tree/master/Sample%20Project"> sample project </a> to the repository.

Thanks,
Jack Rosen

**Comment by sansingh84** [comment]
Thanks a ton Jack, big thanks for the help. 

Regards,
Sandeep

**Comment by sansingh84** [comment]
Hi Jack,

First I want to say thanks for this nice tool for PDF. I have added all annotation successfully in to my project. Only one thing I observed, ad we are using UIView(where we are showing PDF Page) instead of PDFView. We can't use AutoScale on UIView due to that pdf page position is not fix.

Kindly let me know is this can be fix from App side or we have to do some modification on POD.

Thanks in advance.


Regards,

Sandeep Singh

+91-8050297077

________________________________

**Comment by jrosen081** [comment]
Hi Sandeep,

Thank you very much for the praise. You are correct that since PDFDrawingView is a UIView, there is no autoScale property. Even though this is true, I have set up the PDFDrawingView so that the PDF is drawn and scaled to the size of the PDFDrawingView. My guess is that the view that you are using is not the full size of what you want. This is actually an issue in the sample app, and I am working to fix it now.

I hope this helps. If I did not answer your question, please let me know.

Thanks,
Jack

**Comment by sansingh84** [comment]
Hi Jack,

The UIView in which I am displaying the PDF is set (0,0,0,0), this is same as when I used PDFView. Only catch is due to Autoscale is not available pdf is not fitting appropriately on the View.

Please let me know if you fix this then I will test it on my application.

Thanks in advance.

Regards,
Sandeep

**Comment by jrosen081** [comment]
Hi Sandeep,

I have set up the PDFDrawingView to fit into the frame given to it, so that it can be used in many different cases. If you want the PDF to be displayed on the whole page, I would recommend setting up the UIView to have `self.view.frame`(assuming you are creating the view in the View Controller) as its frame, and then give the same frame to the PDFDrawingView.

Thanks,
Jack Rosen

**Comment by sansingh84** [comment]
Hi Jack,

Thanks for reply, today I tested my app & found few functionality is impacted due to the change of View type(UIView instead of PDFView). Is there any way where I can make your POD compatible if I am using PDFKit.

Kindly let me know if it is possible or not & really sorry for disturbing you a lot.


Regards,

Sandeep Singh


________________________________

**Comment by jrosen081** [comment]
Hi Sandeep,

The pod was created as a "replacement" for a PDFView that had built-in drawing/highlighting functionality. I am not sure what functionality you are looking for, but it does not work with a PDFView.

Thanks,
Jack
