### ISSUE TITLE
Can't find attribute Style in PDFDrawingView

### ISSUE THREAD

**Issue by tutmgch15002** [jrosen081/PDFDrawingView#2]
I can't find Style (horizontal or vertical) attribute when I init new PDFDrawingView.
My code only work with `PDFDrawingView(frame: pdfView.bounds, document: document, delegate: self)`. 
I got the same issue when I run `pod install` in the Sample Code.
`let pdfDrawer = PDFDrawingView(frame: pdfView.bounds, document: document, style: .horizontal, delegate: self)` get "_Expression type '@lvalue CGRect' is ambiguous without more context_"
What should I do? Please help me!

**Comment by jrosen081** [comment]
Hi,

To update to the most current version of the pod, you should run ```pod update``` to have access to the style attribute.

Please let me know if this works.

Thanks,
Jack

**Comment by tutmgch15002** [comment]
It worked for me. Thank you so much! 
Your library is the best for me 👍

**Comment by jrosen081** [comment]
You are very welcome. Thank you so much for the praise. I am going to close this issue unless there is anything else I can help with.

Thanks,
Jack
