### ISSUE TITLE
Please, make a project version without cocoa pods

### ISSUE THREAD

**Issue by frankai** [jrosen081/PDFDrawingView#3]
macOS Catalina future users will be very grateful if you remove cocoa pods from the project... ;)

**Comment by frankai** [comment]
Btw, very interesting project! Thanks for your efforts!

**Comment by jrosen081** [comment]
Hello,

Do you mean that you want me to make a sample project without cocoa pods?

Thanks,
Jack

**Comment by frankai** [comment]
Well, only if you want to do it, yes!

**Comment by jrosen081** [comment]
I have now added a new sample project without cocoa pods. https://github.com/jrosen081/PDFDrawingView/tree/master/SampleNoCocoaPods
